In [3]:
import numpy as np

arr = np.array([[1,2,3], [1,2,3]])
arr.dtype

dtype('int64')

# Data type

In [5]:
arr.astype('int8')

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [9]:
#데이타 타입 변경 
arr = arr = np.array([[1,2,3], [1,2,3]], dtype = np.uint8)
arr.dtype
arr.shape

(2, 3)

In [10]:
arr.reshape([1,6])

array([[1, 2, 3, 1, 2, 3]], dtype=uint8)

In [11]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3], dtype=uint8)

## random array 생성

In [12]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [19]:
arr = arr.reshape([32,2])
arr.shape

(32, 2)

## 3차원으로 늘리기

In [22]:
arr = arr.reshape(-1, 2, 1)
arr.shape

(32, 2, 1)

## Ravel

In [24]:
arr = arr.ravel()
arr.shape

(64,)

In [25]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### np.expand-dims()
안의 값을 유지하되 차원 수를 늘리고 싶을때 사용

In [26]:
arr.shape

(64,)

In [28]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 1, 64)

In [29]:
arr = arr.ravel()
arr.shape

(64,)

In [33]:
arr = np.expand_dims((arr, -1), 0)
arr.shape

(1, 2)