In [82]:
import tensorflow.compat.v1 as tf 
#tf.enable_eager_execution()
tf.disable_v2_behavior()
print(tf.__version__)
tf.set_random_seed(0)

2.1.0


In [83]:
import numpy as np

In [143]:
data = np.array([[1,2,3,4], [1,1,3,0], [-1,-2,-4,2], [2,3,2,-3]])
print(data.shape)
x = data[:, 0:3] #0,1,2 input feature
y = data[:, 3: ] #ground truth label
print(x.shape)
print(y.shape)

xp = tf.placeholder(tf.float32, shape = [None, 3])
yp = tf.placeholder(tf.float32, shape = [None, 1])
w0 = tf.Variable(tf.random_normal([3,3]))
x1 = tf.sigmoid(tf.matmul(xp, w0))

w01 = tf.Variable(tf.random_normal([3,3]))
x11 = tf.sigmoid(tf.matmul(x1, w0))

w02 = tf.Variable(tf.random_normal([3,3]))
x12 = tf.sigmoid(tf.matmul(x11, w0))

w03 = tf.Variable(tf.random_normal([3,3]))
x13 = tf.sigmoid(tf.matmul(x12, w0))


w1 = tf.Variable(tf.random_normal([3, 1]) ) # h = x*w #(Nx1) = (Nx3) * (3 x 1)
h = tf.matmul(x1,w1)# not same as tf.matmul(w1, xp)

loss = tf.reduce_mean(tf.square(h - yp))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(loss)

(4, 4)
(4, 3)
(4, 1)


In [144]:
tf.set_random_seed(0)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('yp',sess.run(yp, feed_dict={yp:y}))
print('xp',sess.run(xp, feed_dict={xp:x}))
print('x1',sess.run(w1))
print('h',sess.run(h, feed_dict = {xp:x}))
print('loss', sess.run(loss, feed_dict = {xp:x, yp:y}))

yp [[ 4.]
 [ 0.]
 [ 2.]
 [-3.]]
xp [[ 1.  2.  3.]
 [ 1.  1.  3.]
 [-1. -2. -4.]
 [ 2.  3.  2.]]
x1 [[-2.2587762]
 [-2.1869473]
 [ 1.9905475]]
h [[-1.877708 ]
 [-2.1959622]
 [-0.2692877]
 [-0.6156299]]
loss 12.551147


In [145]:
#print('train', sess.run(train, feed_dict = {xp:x, yp:y}))

for i in range(5000):
    feed = {xp:x, yp:y}
    #print(sess.run(w1))
    if i % 100 ==0:
        print(i," loss: ", sess.run(loss, feed_dict = feed))
    sess.run(train, feed_dict = feed)

0  loss:  12.551147
100  loss:  5.617667
200  loss:  4.7228026
300  loss:  4.1340623
400  loss:  3.5866199
500  loss:  3.0360034
600  loss:  2.481743
700  loss:  1.951961
800  loss:  1.4774961
900  loss:  1.0791167
1000  loss:  0.76484644
1100  loss:  0.529992
1200  loss:  0.36142367
1300  loss:  0.24373722
1400  loss:  0.16309625
1500  loss:  0.10853919
1600  loss:  0.07195311
1700  loss:  0.04756724
1800  loss:  0.03138279
1900  loss:  0.020674989
2000  loss:  0.013605903
2100  loss:  0.008946659
2200  loss:  0.0058794133
2300  loss:  0.0038618871
2400  loss:  0.0025358354
2500  loss:  0.0016646814
2600  loss:  0.00109253
2700  loss:  0.000716919
2800  loss:  0.0004703835
2900  loss:  0.000308586
3000  loss:  0.00020242663
3100  loss:  0.00013278879
3200  loss:  8.70974e-05
3300  loss:  5.712603e-05
3400  loss:  3.7474354e-05
3500  loss:  2.4581019e-05
3600  loss:  1.6125698e-05
3700  loss:  1.0577559e-05
3800  loss:  6.938384e-06
3900  loss:  4.553217e-06
4000  loss:  2.9890682e-06
