In [1]:
import tensorflow as tf
import numpy as np

/Users/mac/opt/anaconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/mac/opt/anaconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/mac/opt/anaconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/mac/opt/anaconda3/envs/venv/lib/python3

In [14]:
#broadcastion

mx1 = tf.constant([[1,2], [3,4]], dtype = tf.float32)
bias = tf.constant([3,2], dtype=tf.float32)
sum = mx1 + bias
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(sum)

array([[4., 4.],
       [6., 6.]], dtype=float32)

In [6]:
x = tf.constant([[1,2,3], [2,3,1]], dtype = tf.float32)
ax = tf.argmax(x)
print(sess.run(ax))
#argmaz 크기비교 

[1 1 0]


In [15]:
x = tf.constant([[2],[1], [0], [3]], dtype = tf.int32)
xhot = tf.one_hot(x, depth=4)

print(sess.run(xhot), xhot.shape)


[[[0. 0. 1. 0.]]

 [[0. 1. 0. 0.]]

 [[1. 0. 0. 0.]]

 [[0. 0. 0. 1.]]] (4, 1, 4)
